### ISSUE TITLE
LotR scene boxes should be foil

### ISSUE THREAD

**Issue by axxroytovu** [taw/magic-preconstructed-decks#108]
> to whom it may concern, lotr scene box contents aren't correct. they are showing the non-foil versions. not sure if this extends to other similar products
> - eskuche on discord

**Comment by taw** [comment]
@axxroytovu @kodawah What do we do with this one?

**Comment by axxroytovu** [comment]
Oh right. I made this so I wouldn't forget, and then promptly forgot. It's correct and we just need to add the `[foil]` tag on the scene box cards.

**Comment by taw** [comment]
Should be done now.
