### ISSUE TITLE
Deck category for ACR

### ISSUE THREAD

**Issue by davidmartos96** [taw/magic-preconstructed-decks#121]
Should the Assassin's Creed decks have the category "Starter Kit" instead of "Arena Starter Deck"?

Starter Kit it's what has been used in previous editions, like Lord of the Rings (https://mtg.wtf/deck/ltr/gondor-green-white), whereas Arena Starter Decks, unless I'm mistaken, would be for preconstructed decks only found in MTG Arena tutorials.

**Comment by taw** [comment]
Unless it's Arena-only, it shouldn't say Arena.

**Comment by davidmartos96** [comment]
@taw It's not Arena only. Here is the link: https://magic.wizards.com/en/news/announcements/assassins-creed-starter-kit-decklists

**Comment by axxroytovu** [comment]
That's my goof, they definitely should be some instance of "starter-kit" or "arena-kit"

I think "starter-kit" is more correct

**Comment by axxroytovu** [comment]
Fix here: https://github.com/taw/magic-preconstructed-decks/pull/124

**Comment by taw** [comment]
Fix merged, so closing.
