### ISSUE TITLE
40k collector edition decks

### ISSUE THREAD

**Issue by kodabb** [taw/magic-preconstructed-decks#18]
hi,

correct me if i'm wrong but https://github.com/taw/magic-preconstructed-decks/tree/master/data/cmd/40k does not have the "collectors' edition" for the listed decks, aka the ones with surge foils

Basically the list of cards is /mostly/ the same except their collector number is different and has a star at the end, except the commanders that have a completely different number.

Could they be added or is it something to be handled on application side?

Thanks

**Comment by taw** [comment]
It's specific to one product so far, so I don't think code can handle it.

You can submit collector version decklists if you want. They'd just need a lot of version number annotations.

**Comment by taw** [comment]
It's all done now (except we don't have card scans with stars yet, but they will come eventually)
