### ISSUE TITLE
Box sets

### ISSUE THREAD

**Issue by taw** [taw/magic-preconstructed-decks#35]
This repo contains decks, but there are other non-randomized boxed products, and there's no reason to not have them as well.

Type would probably be `box` and no distinction between main / side / commander, all cards would be main. Everything else would work the same.

Especially interesting would be SLD with so many products.

**Comment by axxroytovu** [comment]
I'm good to do the data entry. There are two options:
- Have one large "box" category that is exempt from deck size checks. This is much easier from my end but isn't super descriptive.
- Build individual categories for each product with appropriate size checks. This adds extra work for me but would be more consistent with how the tool currently works.

Besides SLD do you have any specific products that you're looking for? The only ones I can think of that aren't already included are:
- [Complete Sets](https://www.cardkingdom.com/mtg/amonkhet/amonkhet-complete-set-factory-sealed)
- [Land Stations](https://www.tcgplayer.com/product/282290/magic-the-brothers-war-land-station-2022?xid=a61f52889-0de0-4d77-9929-84aca77214a0&Language=English)

**Comment by axxroytovu** [comment]
Here's where I'm working on this: https://github.com/axxroytovu/magic-preconstructed-decks/tree/SLD_drops/data/box/sld

**Comment by taw** [comment]
Do we want to add non-SLD box sets?

**Comment by axxroytovu** [comment]
Do you have an example? I don't know what kind of product you're referencing.

**Comment by taw** [comment]
So there's box products that are just the whole set like FTV, SS1 etc., I don't think there's that much value is in, I guess maybe for sake of completeness.

For other products, there's things like:
* [Holiday Gift Packs](https://www.chaoscards.co.uk/prod/other-sealed-products-magic/magic-the-gathering-holiday-gift-pack-2017)
* [SDCC boxes](https://www.cardkingdom.com/mtg-sealed/sdcc-2013-box-set-set-of-five-planeswalkers)
* [Ponies: The Galloping](https://mtg.fandom.com/wiki/Ponies:_The_Galloping)
* [land stations](https://www.chaoscards.co.uk/prod/other-sealed-products-magic/magic-the-gathering-land-station-2022) 

I don't think any of that is terribly important. We could either add them, or decide that we're done with this issue.

**Comment by taw** [comment]
Yeah, all of this looks pretty low priority.

**Comment by axxroytovu** [comment]
I'm tracking sets & products that are missing homes here: https://github.com/mtgjson/mtgjson/issues/1070

If you find any specific products or sets that are missing things feel free to mention it there.

**Comment by taw** [comment]
I currently follow mtgjson by ignoring zero-card sets and assigning their products to best matching set with cards.

**Comment by axxroytovu** [comment]
Then that same procedure needs to be implemented for the sealed products. I don't know how to make that happen besides putting up and tracking the problems as they come up.

**Comment by taw** [comment]
I think we're done here now? Not counting SLD boxes coming out every month?

**Comment by axxroytovu** [comment]
I'm still working through new products and there are definitely things I haven't uploaded yet. Secret Lairs are still coming out, and I'm still loading the deck builder's toolkits and lots of the promo boxes like the SDCC ones. 

I don't really know that leaving this issue open is really doing anything though. The issue is more over at

**Comment by taw** [comment]
OK, closing this issue then.
