### ISSUE TITLE
What printing of Kenrith, the Returned King in Allied Fires Challenger Deck (THB)?

### ISSUE THREAD

**Issue by magreenblatt** [taw/magic-preconstructed-decks#42]
I'm trying to correctly identify the contents of the Allied Fires Challenger Deck: https://github.com/taw/magic-preconstructed-decks/blob/master/data/challenger/thb/Allied%20Fires.txt

There appear to be 5 printings of Kenrith, the Returned King: https://scryfall.com/card/eld/303/kenrith-the-returned-king

The Throne of Eldraine (ELD) version is a buy-a-box promo, so I wouldn't think that would be included in a Challenger Deck.

Do you know if a Multiverse Legends (MUL) version of this card was included in Allied Fires? Or am I missing something?

Thanks.

**Comment by taw** [comment]
[You can view the decks at mtg.wtf](https://mtg.wtf/deck/thb/allied-fires). Other than basics and similar cards, every printing should be accurate.

In this case, [it is indeed buy-a-box promo version](https://youtu.be/BbEkSzjZq8o?t=242).

There's been quite a few cases where cards with "buy a box" promo printed on them were also included in other products like collector boosters.

**Comment by axxroytovu** [comment]
Yeah, when those challenger decks were released the only valid printing was the ELD one.

**Comment by magreenblatt** [comment]
Thanks, that helps :)
