### ISSUE TITLE
Add some annotations for what kind of "deck" it is

### ISSUE THREAD

**Issue by taw** [taw/magic-preconstructed-decks#68]
There's a lot of things in this dataset that aren't really precons.

There's a type field, but that's just whatever WotC labelled it as, and they've not been super consistent.

I think two extra fields would help.

* `category`: `"deck", "halfdeck", "box", "guide"` (and maybe some non tournament legal precon WCxx?)
* `format`: `"casual", "standard", "commander", "modern", "pioneer", "brawl", "archenemy", "planechase"`
* `format` is always `null` for boxes, and always non-`null` for everything else

Issues where I have an answer (but please comment if you have a different opinion):

- [x] 30 card halfdecks legality - M15 actually had Standard legal halfdecks like [this](https://mtg.wtf/deck/m15/black-deck), I think they should be `category: "halfdeck", format: "standard"` as you were supposed to mash two of them and it would result in a tournament legal deck
- [x] Jumpstarts-19? The list is not even actual halfdeck, the halfdeck is that plus one random card (in display field). I think it's best to just make it `category: "halfdeck", format: "jumpstart"` and be done with it
- [x] Should casual subformats like jumpstart, archenemy, planechase get their own specific format values? I'm leaning towards yes as it doesn't really cost us anything
- [x] about 2/3 of non-SLD boxes (and 1/6 of SLD boxes) only consist of Standard-legal cards. Is there any value in making distinction between `category: "box", format: "standard"` vs `category: "box", format: "casual"`, or just leave them all as `category: "box", format: null`? (and they've been a few boxes specifically for Commander like CM1). I'm leaning towards leaving it as `null`
- [x] MOC is `format: "planechase commander"`
- [x] undersized precons consisting of only 40 (or less) Standard legal cards format are `format: "casual standard"`
- [x] a few sets (W17, C20) had minor release time legality mess, I'll just adjust it in legality checker
- [x] what was the format of WC97? WC98+ was all Standard, but it doesn't seem to work fdor WC97. https://mtg.fandom.com/wiki/Jakub_Slemr says the format was "Special", so I guess `format: "casual"` (even though WC is the exact opposite of "casual")
- [x] Arena format situation is a mess, so I'll tag all of them as `format: "arena"`, some are Standard, some are Standard+ANB (is that a real format on Arena?)
- [x] 2 precons and 2 guides contained banned cards. Somehow the precon with Stoneforge Mystic didn't, I guess it got banned just slightly after its release.
- [x] it looks like "Arena Starter Deck" and similar are randomly standard legal or not, what's the intended format for it? I just marked them all as `format: "arena"`, as Arena did a lot of weird things with formats over time. About half of `format: "arena"` decks were legal for Arena Standard
- [x] of 4 "Spellslinger Starter Kit" decks, 3 are Standard legal, and 1 almost-so but has a single GNT card (confirmed in unboxing videos), wtf?

Still open issues:

- [ ] WCxx? are they `category: "deck", format: "standard"` even though they're explicitly not tournament legal?
- [ ] do we need extra platform field (paper deck vs in game deck?)

**Comment by axxroytovu** [comment]
I think we also need format:Shandalar, alchemy, brawl, jumpstart

The WCxx decks are format:null because the cards aren't legal for play.

**Comment by taw** [comment]
Weren't WCxx literally from Standard tournaments, except in non-tournament legal printings? I'm not sure if that's format: standard, or format: null.

**Comment by taw** [comment]
[I started adding some categories](https://github.com/taw/magic-preconstructed-decks/blob/master/lib/deck_types.rb).

There's some weird small products (are they all box?). I'll also need to check if all intro/theme/mtgo/etc. decks are same format or not.

**Comment by kodawah** [comment]
> Weren't WCxx literally from Standard tournaments, except in non-tournament legal printings? I'm not sure if that's format: standard, or format: null.

WCxx was but PTC decks had a variation in which 5 non-standard cards were added -- given the weird state, maybe a spearate category is needed? `memorabilia`?

what's the usecase for adding a format like "standard" or "brawl" given these are rotational?

**Comment by taw** [comment]
Here's the decks format checker flags, either for not being the format they say, or for being Standard when they're tagged casual:

```
["anb", "Azure Skies", 60, "Arena Starter Deck", "deck", "casual", "UNEXPECTED STD"]
["anb", "Azure Skies 2", 60, "Arena Starter Deck", "deck", "casual", "UNEXPECTED STD"]
["anb", "Destructive Firepower", 60, "Arena Starter Deck", "deck", "casual", "UNEXPECTED STD"]
["anb", "Dome Destruction", 60, "Arena Starter Deck", "deck", "casual", "UNEXPECTED STD"]
["anb", "Forest's Might", 60, "Arena Starter Deck", "deck", "casual", "UNEXPECTED STD"]
["anb", "Forest's Might 2", 60, "Arena Starter Deck", "deck", "casual", "UNEXPECTED STD"]
["anb", "Out for Blood", 60, "Arena Starter Deck", "deck", "casual", "UNEXPECTED STD"]
["anb", "Out for Blood 2", 60, "Arena Starter Deck", "deck", "casual", "UNEXPECTED STD"]
["snc", "Earth Shakers", 60, "Starter Kit", "deck", "casual", "UNEXPECTED STD"]
["snc", "Up and Away", 60, "Starter Kit", "deck", "casual", "UNEXPECTED STD"]
["dmu", "Sneak Squad", 60, "Arena Promotional Deck", "deck", "casual", "UNEXPECTED STD"]
["one", "Vivien's Hunt", 60, "Arena Promotional Deck", "deck", "casual", "UNEXPECTED STD"]
["uds", "Enchanter - Enhanced Deck", 75, "Enhanced Deck", "guide", "standard", "FAIL"]
* Time Spiral
["uds", "Fiendish Nature - Enhanced Deck", 75, "Enhanced Deck", "guide", "standard", "FAIL"]
* Recurring Nightmare
["m19", "Red-White Deck", 60, "Spellslinger Starter Kit", "deck", "standard", "FAIL"]
* Inspiring Captain
["m19", "Tactical Assault", 60, "Arena Starter Deck", "deck", "standard", "FAIL"]
* Spiritual Guardian
* Inspiring Commander
* Angelic Reward
* Tactical Advantage
* Confront the Assault
["m20", "Azorius Senate", 60, "Arena Starter Deck", "deck", "standard", "FAIL"]
* Empyrean Eagle
* Raise the Alarm
["m20", "Gruul Clans", 60, "Arena Starter Deck", "deck", "standard", "FAIL"]
* Leafkin Druid
["q07", "Mono White Aggro", 75, "Challenger Deck", "deck", "standard", "FAIL"]
* Faceless Haven
["snc", "Storm of Blades", 60, "Arena Starter Deck", "deck", "standard", "FAIL"]
* Usher of the Fallen
["q08", "Izzet Phoenix", 75, "Pioneer Challenger Deck", "deck", "pioneer", "FAIL"]
* Expressive Iteration
```

**Comment by taw** [comment]
OK, this is working well enough that I included it in json exports. We can tweak the edge cases. Please report any issues you have.

**Comment by taw** [comment]
If nobody has any issues with current implementation, I'm going to close it. Let me know if it's working for you.
