### ISSUE TITLE
Commander Deck display commanders

### ISSUE THREAD

**Issue by axxroytovu** [taw/magic-preconstructed-decks#78]
The thick display commander cards are not represented anywhere and should be included in the sideboard for commander decks.

**Comment by taw** [comment]
I added extra section "Bonus" to decklists, [like here](https://github.com/taw/magic-preconstructed-decks/blob/master/data/cmd-pc/who/Blast%20from%20the%20Past.txt).

Right now it's merged with sideboard by indexer. For now the only difference is that there's no warning printed that number of cards is unexpected. But I'd like to separate it later. In principle tokens etc. could also go there.

I'm not particularly attached to the name "Bonus", but "Additional Contents" is a bit long, and I couldn't come with anything else.

**Comment by axxroytovu** [comment]
> I'm not particularly attached to the name "Bonus", but "Additional Contents" is a bit long, and I couldn't come with anything else.

Maybe "Extra"?

**Comment by kodawah** [comment]
I like Extra, but maybe we could keep them both?

After all the Bonus category could be for cards that were "unexpected" (like the sld promos) while the Extra section could be used for anything (known) but not useful for the deck, like thick or oversized cards

**Comment by taw** [comment]
We could make arbitrary number of sections to really annotate "Planar Deck", "Attraction Deck", "Contraption Deck", "Display Commander", "Tokens" etc., but it feels like a bit much for now.

Precons that aren't decks or half-decks probably should just have one main section. (unless we do Tokens at some point)

**Comment by kodawah** [comment]
tangentially related https://github.com/taw/magic-preconstructed-decks/pull/82

I added the bonus card in the bonus section, I'm still not convinced the thick display cards should be in there too

**Comment by taw** [comment]
Changed the format again and got rid of "Bonus" name. [Example](https://github.com/taw/magic-preconstructed-decks/blob/master/data/cmd-pc/who/Blast%20from%20the%20Past.txt):

```
<maindeck cards>
...
2 Plains
2 Island
3 Forest

Commander
1 The Fourth Doctor [foil] [WHO:2]
1 Sarah Jane Smith [foil] [WHO:6]

Planar Deck
1 The Pyramid of Mars
1 Caught in a Parallel Universe
1 Gardens of Tranquil Repose
1 Spectrox Mines
1 Coal Hill School
1 UNIT Headquarters
1 The Cheetah Planet
1 Antarctic Research Base
1 The Cave of Skulls
1 TARDIS Bay

Display Commander
1 The Fourth Doctor [foil] [WHO:193]
```

**Comment by taw** [comment]
I dropped "Additional Commander".

Sections "Planar Deck" and "Display Commander" are now [displayed in the UI](https://mtg.wtf/deck/who/blast-from-the-past).

They're still exported as part of the sideboard for compatibility.

**Comment by taw** [comment]
I created https://github.com/taw/magic-preconstructed-decks/issues/85 for finishing this system.

**Comment by taw** [comment]
I think this is done. Feel free to reopen if there's anything left to do.
