### ISSUE TITLE
SLD Walking Dead using wrong card versions

### ISSUE THREAD

**Issue by axxroytovu** [taw/magic-preconstructed-decks#79]
Transfer of https://github.com/mtgjson/mtgjson/issues/1119

The Walking Dead Secret Lair Drop is being populated with the new SLX versions of the cards rather than what actually come in the lair.
I.E Greymond, Avacyn's Stalwart in lieu of Rick, Steadfast Leader. Even if "errata'd" to be the same card - there should be a distinction made for these sealed product lists.

**Comment by taw** [comment]
Sorry, which one? [This one?](https://mtg.wtf/deck/sld/the-walking-dead-foil)

**Comment by axxroytovu** [comment]
I guess so. I'm just transferring over the issue. I also think it's correctly loading into MTGJson so I'll ask further about what the problem is.

**Comment by taw** [comment]
@axxroytovu  Any updates on this?

**Comment by taw** [comment]
@axxroytovu  Is this fixed and should I close this issue?

**Comment by axxroytovu** [comment]
I haven't gotten any responses so I'd close it.
