### ISSUE TITLE
Incorrect set codes

### ISSUE THREAD

**Issue by magreenblatt** [taw/magic-preconstructed-decks#8]
The decks for "Portal Second Age" are in a folder named `data/theme-40/po2`, but the set code should be p02 (number zero instead of letter oh) [1].

The decks for "Nemesis" are in a folder named `data/theme/nms`, but the set code should be nem [2].

[1] https://mtg.gamepedia.com/Portal_Second_Age
[2] https://mtg.gamepedia.com/Nemesis

**Comment by taw** [comment]
That might be leftover from MCI / mtgjson v3 codes.

**Comment by taw** [comment]
Both renamed now.
