### ISSUE TITLE
Threre is a colon in a deck name

### ISSUE THREAD

**Issue by 8ullyMaguire** [taw/magic-preconstructed-decks#84]
In order to enable downloading everything at once, it is necessary to filter out forbidden characters from deck names.

The following characters are forbidden:

- Windows: < (less than), > (greater than), : (colon), " (double quote), / (forward slash), \ (backslash), | (vertical bar or pipe), ? (question mark), * (asterisk)
- Linux/Unix: / (forward slash), \0 (null byte)

I'm doing something like this when converting from .json to .dck:

```ruby
FORBIDDEN_CHARS = ['<', '>', ':', '"', '/', '\\', '|', '?', '*']

def clean_deck_name(name)
  name.downcase.gsub(' ', '_').delete(FORBIDDEN_CHARS.join)
end
```

**Comment by 8ullyMaguire** [comment]
Although this is not really something I want, just an observation.

**Comment by magreenblatt** [comment]
Please also rename the file that currently contains a colon.

Checking out that file fails on Windows with:
```
error: invalid path 'data/cmd/pagl/Angels: They're Just Like Us but Cooler and with Wings.txt'
```
The workaround is to run `git config core.protectNTFS false` first (or `git clone -c core.protectNTFS=false <repo_url>` for a new checkout), however that file is then deleted in the local checkout:
```
Changes not staged for commit:
        deleted:    data/cmd/pagl/Angels: They're Just Like Us but Cooler and with Wings.txt
```

**Comment by taw** [comment]
Yeah, I can change it.

**Comment by taw** [comment]
I renamed that one file. Are there any other problematic files?

**Comment by magreenblatt** [comment]
Just the one, thanks.On Nov 3, 2023, at 08:46, Tomasz Wegrzanowski ***@***.***> wrote:﻿
I renamed that one file. Are there any other problematic files?

**Comment by taw** [comment]
OK, closing it as done then.
